#!/bin/sh
ref_dir=$(pwd)
custom_dir="$HOME/.config/nvim/lua/custom"
if [ ! -d "${custom_dir}" ]; then
  echo "Create ${custom_dir} before running this script"
  exit 0
fi
pushd $custom_dir
ln -fs "$ref_dir/"* .
